### ISSUE TITLE
Change wording in introscreen app: Wallet

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#439] opened 2022-04-22 09:41 UTC
Remove "More currencies are to be added in the future"

**Comment by sabrinasadik** [comment] 2022-04-22 10:25
![photo_2022-04-22 12 24 52](https://user-images.githubusercontent.com/31733464/164691707-aeff102b-3f57-4a68-b14d-b1ecd1a5662c.jpeg)

**Comment by AlaaElattar** [comment] 2024-10-21 09:37
duplicate of https://github.com/threefoldtech/threefold_connect/issues/440

**Closed by AlaaElattar** 2024-10-21 09:37 UTC
Labels: type_feature
