### ISSUE TITLE
Email address requires re-verification

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#310] opened 2021-10-14 07:37 UTC
### Summary

Removing the account in the app and then recovering it, requires the email address to be re-verified.

### Environments

*   Android OS v11
*   iOS v14.7

### Version

*   App: 3.1.0-132
*   Wallet: 2.8.2-HF01

### Steps to reproduce

1.  Open the app and select "SIGN UP" option and go through the registration process.
2.  Verify your email address using the verification link in the received email.
3.  Navigate to _Settings_ screen, your email address should be labeled as _Verified_ (screenshot 2).
4.  Expand _Advanced settings_ section.
5.  Click on _Remove Account From Device_ option and select _Yes_ on the confirmation dialog (screenshot 2).
6.  Select _RECOVER ACCOUNT_ option.
7.  Add your account credentials to recover.
8.  Navigate to _Settings_ screen, the email address is labeled as _Unverified_ (screenshot 1).

### Current behavior

The email address requires re-verification whenever an account is recovered in the app.

### Expected behavior

The email address should be verified once.

**Comment by ken-de-moor** [comment] 2021-10-14 07:44
Will be fixed with new KYC implementation,

Can be invalidated after https://github.com/threefoldtech/threefold_connect/issues/299 is delivered to production.

**Comment by jdelrue** [comment] 2021-11-03 09:51
Is as intended, but as Ken says this is fixed in the new version

**Closed by jdelrue** 2021-11-03 09:51 UTC
