### ISSUE TITLE
Qr-code scan is not working

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/threefold_connect#370] opened 2022-01-10 09:57 UTC
![image](https://user-images.githubusercontent.com/26298009/148747148-cf06153e-c7fd-4d5c-9ffc-5856b59fd9d7.png)

**Comment by ken-de-moor** [comment] 2022-01-19 14:37
Duplicate of https://github.com/threefoldtech/threefold_connect/issues/360

Also not a TF connect issue.

If the phone camera can't read it, there is nothing TF connect can do to change that.

**Closed by ken-de-moor** 2022-01-19 14:37 UTC
Labels: type_bug
