### ISSUE TITLE
Stellar Wallet Secret works correctly despite the addition of extra Character 

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/threefold_connect#695] opened 2024-10-31 04:53 UTC
### Description:

- The secret input field for adding a Stellar wallet allows entry of the secret key plus one additional character and it works correctly after clicking on save.

### Steps to Reproduce:
1.Open the TF-Connect App .
2.Click on "Wallet" in menu items.
3.Write your PIN code.
4.Click on "+" Symbol on the top right of the page.
5.Write Wallet name in "Wallet Name" and Stellar address in "Secret"
6.Add one more Character (57 Character instead of 56)
6.Click on "Save" button.

### Expected Behavior:

- The Secret input should not accept wrong length for the Stellar secret key

### Screenshot Of the Issue:

- 

https://github.com/user-attachments/assets/c6adb163-b705-4d02-8388-60c441d4fb1b

### Environment:

 • OS Version: Android 14
 • App Version: 3.9.1

**Comment by zaelgohary** [comment] 2024-11-06 14:27
Work completed:

The issue happened because the generateHexSeed returned the same value for both `secret` & `secret + a`. The issue is from stellar_flutter_sdk package. Fixed by checking the seed length before generating hex.

**Comment by khaledyoussef24** [comment] 2024-11-10 13:44
verified 
IOS 18
Version 4.0.0
Issue is no longer reproducible
![Image](https://github.com/user-attachments/assets/6ac7d923-e925-4189-8092-eb77673a9f76)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4412610)

**Closed** 2024-11-11 09:53 UTC
Labels: type_bug
