### ISSUE TITLE
Cannot change email identity after verifying another email

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/threefold_connect#748] opened 2024-11-12 02:34 UTC
### Description:
- After verifying a new email address in identity page of the Threefold Connect App, I am unable to change the email identity. with alert message "something went wrong"

### Steps to Reproduce:
1.Open the application.
2.Click on "Identity" in menu items.
3.Click on the email icon.
4.Enter a valid email address in the "Change email" field.
5.Click on "Ok".

### Screenshot Of the Issue:
![image](https://github.com/user-attachments/assets/319d1179-e723-4474-ab15-c910544c7c1c)

### Environment:

 • OS Version: Android 14
 • App Version: 4.0.0-181

**Comment by AhmedHanafy725** [comment] 2024-11-12 06:01
duplicate of 
- #647

**Closed by AhmedHanafy725** 2024-11-12 06:01 UTC
