### ISSUE TITLE
Taking screenshot with three fingers in wallet page, makes the wallet page stuck

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/threefold_connect#205] opened 2021-02-01 11:59 UTC
### Steps
1- Open the app.
2- Go to the wallet page.
3- Take a screenshot with three fingers.

### Result
The wallet page stuck.

https://user-images.githubusercontent.com/41957921/106455769-4ece9c00-6495-11eb-8dc9-d1ec79129a5c.mp4

**Comment by jdelrue** [comment] 2021-02-23 08:17
To be tested with wallet debug

**Comment by ken-de-moor** [comment] 2021-04-13 07:59
@AhmedHanafy725 fixed on my device with newest webview update, but this might be device specific, could you revalidate please?

**Comment by AhmedHanafy725** [comment] 2021-04-13 15:08
just updated the app and tried again, but it's still happening
my device: Honor 8x, Andriod version 10

**Comment by ken-de-moor** [comment] 2021-06-21 06:23
@AhmedHanafy725 we can't reproduce it anymore on any of our devices, so honestly we don't know if it's fixed or not. But we have done several wallet updates since then. Could you kindly retest if it still happens after these updates?

**Closed** 2021-08-02 09:15 UTC
Labels: type_bug
